[package]
name = "kmod"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-27.tar.xz"
sha512 = "e0513094935333fca1fb4c3e3493b232507a579ab00a6457cc9ed3e928363d05aad80634fb65a8287a336bf9895194c7be8ddc41bb088a6c2cca44fc1bfbdb6c"

[build-dependencies]
glibc = { path = "../glibc" }
