[package]
name = "coreutils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-8.31.tar.xz"
sha512 = "ef8941dae845bbf5ae5838bc49e44554a766302930601aada6fa594e8088f0fbad74e481ee392ff89633e68b99e4da3f761fcb5d31ee3b233d540fe2a2d4e1af"

[build-dependencies]
glibc = { path = "../glibc" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
