[package]
name = "thar-be-settings"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
reqwest = { version = "0.9", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
handlebars = "1.1"
derive-error = "0.0"
apiserver = { path = "../apiserver" }
log = "0.4"
stderrlog = "0.4"
itertools = "0.8"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
