[package]
name = "libpcre"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://ftp.pcre.org/pub/pcre/pcre2-10.34.tar.bz2"
sha512 = "77ad75f8b0b8bbfc2f57932596151bca25b06bd621e0f047e476f38cd127f43e2052460b95c281a7e874aad2b7fd86c8f3413f4a323abb74b9440a42d0ee9524"

[build-dependencies]
glibc = { path = "../glibc" }
