[package]
name = "schnauzer"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiclient = { path = "../apiclient" }
base64 = "0.11"
bottlerocket-release = { path = "../../bottlerocket-release" }
erased-serde = "0.3"
handlebars = "3.0"
http = "0.1"
log = "0.4"
models = { path = "../../models" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
