[package]
name = "signpost"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
gpt = "0.6.1"

[profile.release]
debug = true
