[package]
name = "moondog"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiclient = { path = "../apiclient" }
apiserver = { path = "../apiserver" }
http = "0.1"
tracing = "0.1"
reqwest = { version = "0.9", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
snafu = "0.5"
tracing-subscriber = "0.1"
toml = "0.5"

[build-dependencies]
cargo-readme = "3.1"
