[package]
name = "moondog"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
# FIXME Using rustls until openssl is packaged.
reqwest = { version = "0.9", default-features = false, features = [ "rustls-tls" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
toml = "0.4"
derive-error = "0.0"
log = "0.4"
stderrlog = "0.4"

[build-dependencies]
cargo-readme = "3.1"
