[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.28.tar.gz"
sha512 = "eb89d3a4da986790d3679195f00dd907370e109acea65c19d60ea5ae5916a138370121b154cc7261a1ed4d403bfead002cfa160bf8f3473564c5f4c5f7ce6df9"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
