# OS-level defaults.
# Should match the structures in the model definition.

[settings]
timezone = "America/Los_Angeles"
hostname = "localhost"

[settings.updates]
metadata-base-url = "https://d25d9m6x9pxh9h.cloudfront.net/45efedef4afe/metadata/"
target-base-url = "https://d25d9m6x9pxh9h.cloudfront.net/45efedef4afe/targets/"

[services.hostname]
configuration-files = ["hostname"]
restart-commands = []

[configuration-files.hostname]
path = "/etc/hostname"
template-path = "/usr/share/templates/hostname"

[metadata.settings.hostname]
affected-services = ["hostname"]

# Container runtime.

[services.containerd]
configuration-files = ["containerd-config-toml"]
restart-commands = []

[configuration-files.containerd-config-toml]
path = "/etc/containerd/config.toml"
template-path = "/usr/share/templates/containerd-config-toml_aws-k8s"

# Kubernetes.

[services.kubernetes]
configuration-files = ["kubelet-env", "kubelet-config", "kubelet-kubeconfig", "kubernetes-ca-crt"]
restart-commands = []

[configuration-files.kubelet-env]
path = "/etc/kubernetes/kubelet/env"
template-path = "/usr/share/templates/kubelet-env"

[configuration-files.kubelet-config]
path = "/etc/kubernetes/kubelet/config"
template-path = "/usr/share/templates/kubelet-config"

[configuration-files.kubelet-kubeconfig]
path = "/etc/kubernetes/kubelet/kubeconfig"
template-path = "/usr/share/templates/kubelet-kubeconfig"

[configuration-files.kubernetes-ca-crt]
path = "/etc/kubernetes/pki/ca.crt"
template-path = "/usr/share/templates/kubernetes-ca-crt"

[metadata.settings.kubernetes]
max-pods.setting-generator = "pluto max-pods"
cluster-dns-ip.setting-generator = "pluto cluster-dns-ip"
node-ip.setting-generator = "pluto node-ip"
affected-services = ["kubernetes"]

[metadata.settings.kubernetes.pod-infra-container-image]
setting-generator = "pluto pod-infra-container-image"
affected-services = ["kubernetes", "containerd"]

# Updog.

[services.updog]
configuration-files = ["updog-toml"]
restart-commands = []

[configuration-files.updog-toml]
path = "/etc/updog.toml"
template-path = "/usr/share/templates/updog-toml"

[metadata.settings.updates]
affected-services = ["updog"]
seed.setting-generator = "bork seed"

# HostContainers

[settings.host-containers.admin]
enabled = false
source = "328549459982.dkr.ecr.us-west-2.amazonaws.com/thar-admin:v0.2"
superpowered = true

[settings.host-containers.control]
enabled = true
source = "328549459982.dkr.ecr.us-west-2.amazonaws.com/thar-control:v0.2"
superpowered = false

[services.host-containers]
configuration-files = []
restart-commands = ["/usr/bin/host-containers"]

[metadata.settings.host-containers]
affected-services = ["host-containers"]

# NTP

[settings.ntp]
time-servers = ["169.254.169.123", "2.amazon.pool.ntp.org"]

[services.ntp]
configuration-files = ["chrony-conf"]
restart-commands = ["/bin/systemctl try-reload-or-restart chronyd.service"]

[configuration-files.chrony-conf]
path = "/etc/chrony.conf"
template-path = "/usr/share/templates/chrony-conf"

[metadata.settings.ntp]
affected-services = ["chronyd"]
