[package]
name = "strace"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://strace.io/files/5.4/strace-5.4.tar.xz"
sha512 = "4ddba2ec4457a2257c18b26dca851e49a275813c4eb3069379a93fcc60228f9b63a3dee9e3719ae606a7cc61d55ab21ce147327223903c302c061e381097a8d7"

[build-dependencies]
glibc = { path = "../glibc" }
