[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
reqwest = { version = "0.9", default-features = false, features = []}
serde_json = "1"
snafu = "0.5"
tracing = "0.1"
tracing-subscriber = "0.1"

[build-dependencies]
cargo-readme = "3.1"
