[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
actix-web = { version = "1.0.5", default-features = false, features = ["uds"] }
libc = "0.2"
log = "0.4"
models = { path = "../../models" }
nix = "0.15.0"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.7"
snafu = "0.5"
systemd = { version = "0.4.0", default-features = false, features = [], optional = true }
walkdir = "2.2"

[features]
default = ["sd_notify"]

sd_notify = ["systemd"]

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
toml = "0.5"
