[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
actix-web = { version = "1.0.5", default-features = false, features = ["uds"] }
base64 = "0.10"
lazy_static = "1.2"
tracing = "0.1"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.5"
tracing-subscriber = "0.1"
toml = "0.5"
walkdir = "2.2"
systemd = { version = "0.4.0", default-features = false, features = [], optional = true }
nix = "0.15.0"
libc = "0.2"

[features]
default = []

sd_notify = ["systemd"]

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
