[package]
name = "apiserver"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
actix-web = { version = "1.0.5", default-features = false, features = ["uds"] }
base64 = "0.10"
lazy_static = "1.2"
log = "0.4"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.5"
stderrlog = "0.4"
toml = "0.5"
walkdir = "2.2"

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"
