# OS-level defaults.
# Should match the structures in src/model.rs and fill every field.

[settings]
timezone = "America/Los_Angeles"
hostname = "localhost"

[services.hostname]
configuration-files = ["hostname"]
restart-commands = []

[configuration-files.hostname]
path = "/etc/hostname"
template-path = "/usr/share/templates/hostname"

[[metadata]]
key = "settings.hostname"
md = "affected-services"
val = ["hostname"]
