[package]
name = "docker-engine"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/engine/archive/v18.09.9/engine-18.09.9.tar.gz"
sha512 = "070700e5b9dac439fd494ae52824ebbd0a8dbc4bf0351c4173c47f585ab81a0fb39470c4d566a7dc69481b03e04f073727062872d2550505ae67a5d1bb30132e"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }
