[clarify."github.com/gogo/googleapis"]
# license file was added later, see https://github.com/gogo/googleapis/commit/b23578765ee54ff6bceff57f397d833bf4ca6869
expression = "Apache-2.0"
license-files = []

[clarify."github.com/sean-/seed"]
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xd5734f17 },
]
