[package]
name = "apiclient"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
# TODO: update futures/hyper/tokio to new async
futures = "0.1"
http = "0.1"
hyper = "0.12"
hyperlocal = "0.6"
snafu = "0.6"
tokio = "0.1"

[build-dependencies]
cargo-readme = "3.1"
