[package]
name = "updog"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.9"
data_store_version = { path = "../../api/data_store_version" }
log = "0.4"
lz4 = "1.23.1"
rand = "0.7.0"
regex = "1.1"
reqwest = { version = "0.9.17", default-features = false, features = ["rustls-tls"] }
semver = "0.9.0"
serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0.40"
serde_plain = "0.3.0"
signpost = { path = "../signpost" }
simplelog = "0.7"
snafu = "0.5.0"
time = "0.1"
toml = "0.5.1"
tough = { path = "../tough", features = ["http"] }
update_metadata = { path = "../update_metadata" }
structopt = "0.3"

[dev-dependencies]
tempfile = "3.1.0"
