[package]
name = "updog"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
edition = "2018"
publish = false

[dependencies]
lz4 = "1.23.1"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.40"
serde_plain = "0.3.0"
signpost = { path = "../signpost" }
snafu = "0.4.1"
stderrlog = "0.4"
toml = "0.5.1"
tough = { path = "../tough" }
