[package]
name = "docker-cli"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v18.09.9/cli-18.09.9.tar.gz"
sha512 = "bc06dbbe8da1d9eaab509eadb6d6af3b2a603176c5c6b8432641dc0f2843a90f14b16455331540c30fd9b0039cc7936c334da3bdc957afebcf0b5a4caf312b7e"

[build-dependencies]
glibc = { path = "../glibc" }
