[package]
name = "host-ctr"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
source-groups = [ "host-ctr" ]

[lib]
path = "pkg.rs"

[build-dependencies]
glibc = { path = "../glibc" }
