[package]
name = "growpart"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
edition = "2018"

[dependencies]
gptman = { version = "0.5.0", default-features = false }
snafu = "0.6"
libc = "0.2"
block-party = { path = "../updater/block-party" }

[build-dependencies]
cargo-readme = "3.1"
