[package]
name = "login"
version = "0.0.1"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }

[features]
cascade = [
    "glibc",
]
