[package]
name = "wicked"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/openSUSE/wicked/archive/version-0.6.63.tar.gz"
sha512 = "c23529246c545acd5c2342e035bc14d4b967bfbcedc8d7c49077a45bf3f98273ba73949522339569372120109078b53a3c8332d34ec29907841f36a72d413d39"

[build-dependencies]
glibc = { path = "../glibc" }
libdbus = { path = "../libdbus" }
libiw = { path = "../libiw" }
libnl = { path = "../libnl" }
systemd = { path = "../systemd" }
