[package]
name = "storewolf"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiserver = { path = "../apiserver" }
data_store_version = { path = "../data_store_version" }
tracing = "0.1"
rand = { version = "0.7", default-features = false, features = ["std"] }
snafu = "0.5"
tracing-subscriber = "0.1"
toml = "0.5"

[build-dependencies]
cargo-readme = "3.1"
