[package]
name = "storewolf"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
apiserver = { path = "../apiserver" }
data_store_version = { path = "../data_store_version" }
log = "0.4"
models = { path = "../../models" }
rand = { version = "0.7", default-features = false, features = ["std"] }
simplelog = "0.7"
snafu = "0.5"
toml = "0.5"

[build-dependencies]
cargo-readme = "3.1"
