# OS-level defaults.
# Should match the structures in src/model.rs.

[settings]
timezone = "America/Los_Angeles"
hostname = "localhost"

[settings.updates]
metadata-base-url = "https://cdn.thar.amazonlinux.a2z.com/updates/metadata/"
target-base-url = "https://cdn.thar.amazonlinux.a2z.com/updates/targets/"

[services.hostname]
configuration-files = ["hostname"]
restart-commands = []

[configuration-files.hostname]
path = "/etc/hostname"
template-path = "/usr/share/templates/hostname"

[[metadata]]
key = "settings.hostname"
md = "affected-services"
val = ["hostname"]

# Kubernetes.

[services.kubernetes]
configuration-files = ["kubelet-env", "kubelet-config", "kubelet-kubeconfig", "kubernetes-ca-crt"]
restart-commands = []

[configuration-files.kubelet-env]
path = "/etc/kubernetes/kubelet/env"
template-path = "/usr/share/templates/kubelet-env"

[configuration-files.kubelet-config]
path = "/etc/kubernetes/kubelet/config"
template-path = "/usr/share/templates/kubelet-config"

[configuration-files.kubelet-kubeconfig]
path = "/etc/kubernetes/kubelet/kubeconfig"
template-path = "/usr/share/templates/kubelet-kubeconfig"

[configuration-files.kubernetes-ca-crt]
path = "/etc/kubernetes/pki/ca.crt"
template-path = "/usr/share/templates/kubernetes-ca-crt"

[[metadata]]
key = "settings.kubernetes.cluster-dns-ip"
md = "setting-generator"
val = "pluto cluster-dns-ip"

[[metadata]]
key = "settings.kubernetes.node-ip"
md = "setting-generator"
val = "pluto node-ip"

[[metadata]]
key = "settings.kubernetes.pod-infra-container-image"
md = "setting-generator"
val = "pluto pod-infra-container-image"

[[metadata]]
key = "settings.kubernetes"
md = "affected-services"
val = ["kubernetes"]

# Updog.

[services.updog]
configuration-files = ["updog-toml"]
restart-commands = []

[configuration-files.updog-toml]
path = "/etc/updog.toml"
template-path = "/usr/share/templates/updog-toml"

[[metadata]]
key = "settings.updates"
md = "affected-services"
val = ["updog"]

# HostContainers

[settings.host-containers.admin]
enabled = false
source = "328549459982.dkr.ecr.us-west-2.amazonaws.com/thar-admin:v0.1"
superpowered = true

[settings.host-containers.control]
enabled = true
source = "328549459982.dkr.ecr.us-west-2.amazonaws.com/thar-control:v0.1"
superpowered = false

[services.host-containers-admin]
configuration-files = ["host-containers-systemd-unit-admin"]
restart-commands = ["/usr/bin/servicedog -s settings.host-containers.admin.enabled -u host-containers@admin.service"]

[services.host-containers-control]
configuration-files = ["host-containers-systemd-unit-control"]
restart-commands = ["/usr/bin/servicedog -s settings.host-containers.control.enabled -u host-containers@control.service"]

[configuration-files.host-containers-systemd-unit-admin]
path = "/etc/systemd/system/host-containers@admin.service"
template-path = "/usr/share/templates/host-containers-systemd-unit-admin"

[configuration-files.host-containers-systemd-unit-control]
path = "/etc/systemd/system/host-containers@control.service"
template-path = "/usr/share/templates/host-containers-systemd-unit-control"

[[metadata]]
key = "settings.host-containers.admin"
md = "affected-services"
val = ["host-containers-admin"]

[[metadata]]
key = "settings.host-containers.control"
md = "affected-services"
val = ["host-containers-control"]

# NTP

[settings.ntp]
time-servers = ["169.254.169.123", "2.amazon.pool.ntp.org"]

[services.ntp]
configuration-files = ["chrony-conf"]
restart-commands = ["/bin/systemctl try-reload-or-restart chronyd.service"]

[configuration-files.chrony-conf]
path = "/etc/chrony.conf"
template-path = "/usr/share/templates/chrony-conf"

[[metadata]]
key = "settings.ntp"
md = "affected-services"
val = "[chronyd]"
