# OS-level defaults.
# Should match the structures in src/model.rs.

[settings]
timezone = "America/Los_Angeles"
hostname = "localhost"

[settings.updates]
metadata-base-url = "https://d25d9m6x9pxh9h.cloudfront.net/45efedef4afe/metadata/"
target-base-url = "https://d25d9m6x9pxh9h.cloudfront.net/45efedef4afe/targets/"

[services.hostname]
configuration-files = ["hostname"]
restart-commands = []

[configuration-files.hostname]
path = "/etc/hostname"
template-path = "/usr/share/templates/hostname"

[[metadata]]
key = "settings.hostname"
md = "affected-services"
val = ["hostname"]

# Kubernetes.

[services.kubernetes]
configuration-files = ["kubelet-env", "kubelet-config", "kubelet-kubeconfig", "kubernetes-ca-crt", "containerd-config-toml"]
restart-commands = []

[configuration-files.kubelet-env]
path = "/etc/kubernetes/kubelet/env"
template-path = "/usr/share/templates/kubelet-env"

[configuration-files.kubelet-config]
path = "/etc/kubernetes/kubelet/config"
template-path = "/usr/share/templates/kubelet-config"

[configuration-files.kubelet-kubeconfig]
path = "/etc/kubernetes/kubelet/kubeconfig"
template-path = "/usr/share/templates/kubelet-kubeconfig"

[configuration-files.kubernetes-ca-crt]
path = "/etc/kubernetes/pki/ca.crt"
template-path = "/usr/share/templates/kubernetes-ca-crt"

[configuration-files.containerd-config-toml]
path = "/etc/containerd/config.toml"
template-path = "/usr/share/templates/containerd-config-toml"

[[metadata]]
key = "settings.kubernetes.max-pods"
md = "setting-generator"
val = "pluto max-pods"

[[metadata]]
key = "settings.kubernetes.cluster-dns-ip"
md = "setting-generator"
val = "pluto cluster-dns-ip"

[[metadata]]
key = "settings.kubernetes.node-ip"
md = "setting-generator"
val = "pluto node-ip"

[[metadata]]
key = "settings.kubernetes.pod-infra-container-image"
md = "setting-generator"
val = "pluto pod-infra-container-image"

[[metadata]]
key = "settings.kubernetes"
md = "affected-services"
val = ["kubernetes"]

# Updog.

[services.updog]
configuration-files = ["updog-toml"]
restart-commands = []

[configuration-files.updog-toml]
path = "/etc/updog.toml"
template-path = "/usr/share/templates/updog-toml"

[[metadata]]
key = "settings.updates"
md = "affected-services"
val = ["updog"]

[[metadata]]
key = "settings.updates.seed"
md = "setting-generator"
val = "bork seed"

# HostContainers

[settings.host-containers.admin]
enabled = false
source = "328549459982.dkr.ecr.us-west-2.amazonaws.com/thar-admin:v0.2"
superpowered = true

[settings.host-containers.control]
enabled = true
source = "328549459982.dkr.ecr.us-west-2.amazonaws.com/thar-control:v0.2"
superpowered = false

[services.host-containers]
configuration-files = []
restart-commands = ["/usr/bin/host-containers"]

[[metadata]]
key = "settings.host-containers"
md = "affected-services"
val = ["host-containers"]

# NTP

[settings.ntp]
time-servers = ["169.254.169.123", "2.amazon.pool.ntp.org"]

[services.ntp]
configuration-files = ["chrony-conf"]
restart-commands = ["/bin/systemctl try-reload-or-restart chronyd.service"]

[configuration-files.chrony-conf]
path = "/etc/chrony.conf"
template-path = "/usr/share/templates/chrony-conf"

[[metadata]]
key = "settings.ntp"
md = "affected-services"
val = "[chronyd]"
