[package]
name = "block-party"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
snafu = "0.6.0"
