[package]
name = "socat"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "http://www.dest-unreach.org/socat/download/socat-1.7.3.4.tar.bz2"
sha512 = "f338d28e5fd9d7ebb9e30b0fa700bcd5ff50ff9e668403474963a3310ba2b5f68b5236b928872c18e4b1ee95328374987e7e263ac7655a0d9b3fc9da77281123"

[build-dependencies]
glibc = { path = "../glibc" }
