[package]
name = "data_store_version"
version = "0.1.0"
authors = ["mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
lazy_static = "1.2"
log = "0.4"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"

snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
