[package]
name = "containerd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containerd/containerd/archive/v1.2.9/containerd-1.2.9.tar.gz"
sha512 = "60c7d08db3796caa8148f242f8386ff530943cef19fe73c72787fd7bbf2420feac06cadd558afc93d2baf168817d679245bf2ac9feb169547286cb312818be85"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }
golang = { path = "../golang", optional=true }
libseccomp = { path = "../libseccomp", optional=true }

[features]
cascade = [
    "glibc",
    "golang",
    "libseccomp",
]
