[package]
name = "cni-plugins"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containernetworking/plugins/archive/v0.8.3/plugins-0.8.3.tar.gz"
sha512 = "054479a73ddbfbdb2986ac202ae2da7a69ae7bb693a250885f950a26973c60be3053d4e95ca24cf5eb67c104b9af8231f859e22c01a066ce3a206a186fc55a6d"

[build-dependencies]
glibc = { path = "../glibc" }
