[package]
name = "tcpdump"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "http://www.tcpdump.org/release/tcpdump-4.9.2.tar.gz"
sha512 = "e1bc19a5867d6e3628f3941bdf3ec831bf13784f1233ca1bccc46aac1702f47ee9357d7ff0ca62cddf211b3c8884488c21144cabddd92c861e32398cd8f7c44b"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc" }
libpcap = { path = "../libpcap" }
