[package]
name = "growpart"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
source-groups = [
    "growpart",
    "updater/block-party",
]

[lib]
path = "pkg.rs"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }
rust = { path = "../rust", optional=true }

[features]
cascade = [
    "glibc",
    "rust",
]
