root = "/var/lib/host-containerd"
state = "/run/host-containerd"
disabled_plugins = ["aufs", "zfs", "cri"]

[grpc]
address = "/run/host-containerd/containerd.sock"

[plugins.opt]
path = "/opt/host-containerd"
