[package]
name = "models"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
lazy_static = "1.2"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.5"
toml = "0.5"
url = "2.1"

[lib]
name = "model"
path = "current/src/model.rs"
