[package]
name = "migrate-host-containers-v03"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false

[dependencies]
migration-helpers = { path = "../../../migration-helpers" }
schnauzer = { path = "../../../../schnauzer" }
serde_json = "1.0"
snafu = "0.6"
