[package]
name = "pluto"
version = "0.1.0"
authors = ["Michael Patraw <patraw@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
reqwest = { version = "0.9", default-features = false, features = []}
serde_json = "1"
snafu = "0.6"

[build-dependencies]
cargo-readme = "3.1"
